#ifndef SAILTRACK_MODULE_CONFIG_H
#define SAILTRACK_MODULE_CONFIG_H

#define TASK_HIGH_PRIORITY 6
#define TASK_MEDIUM_PRIORITY 4
#define TASK_LOW_PRIORITY 2

#define TASK_BIG_STACK_SIZE 8192
#define TASK_MEDIUM_STACK_SIZE 4096
#define TASK_SMALL_STACK_SIZE 2048

#define WIFI_SSID "SailTrack-Net"
#define WIFI_PASSWORD "sailtracknet"
#define WIFI_CONNECTION_TIMEOUT_MS 10 * 1e3
#define WIFI_SLEEP_DURATION_US 60 * 1e6
#define WIFI_GATEWAY IPAddress(192, 168, 42, 1)
#define WIFI_SUBNET IPAddress(255, 255, 255, 0)

#define MQTT_SERVER "192.168.42.1"
#define MQTT_PORT 1883
#define MQTT_USERNAME "mosquitto"
#define MQTT_PASSWORD "dietpi"
#define MQTT_CONNECTION_TIMEOUT_MS 20 * 1e3
#define MQTT_OUTPUT_BUFFER_SIZE 800

#define STATUS_PUBLISH_RATE 0.1
#define STATUS_PUBLISH_PERIOD_MS 1000 / STATUS_PUBLISH_RATE

#define LOG_PUBLISH_RATE 0.1
#define LOG_PUBLISH_PERIOD_MS 1000 / LOG_PUBLISH_RATE

#define OTA_HANDLE_RATE 1
#define OTA_HANDLE_PERIOD_MS 1000 / OTA_HANDLE_RATE

#endif
